### ISSUE TITLE
Latest Windows 10 update.

### ISSUE THREAD

**Issue by ksbansal** [Lolginer/Albedo#10]
After the latest update Albedo is not showing up in the system tray making it unusable. Please fix as soon as possible. Thank you in advance.

**Comment by farazs** [comment]
I'm having the same issue. My computer just restarted after updating and I cannot get Albedo to start.

**Comment by Lolginer** [comment]
I'm on the latest update. There shouldn't be any compatibility issues. 

What happens if you run C:\Program Files (x86)\Albedo\Albedo.exe? Is it running in the task manager?

**Comment by farazs** [comment]
It runs for about 30 seconds in the task manager then is gone. It never shows up in the taskbar.

**Comment by Lolginer** [comment]
That's really odd. Could you go to %localappdata%/Albedo and upload the latest user.config you can find? It's okay if you edit out bridgeUserName.

What happens if you uninstall Albedo and reinstall it?

**Comment by ksbansal** [comment]
Uninstalling and reinstalling does nothing

**Comment by farazs** [comment]
Couldn't upload the file directly. Here it is in a zip.
[user.zip](https://github.com/Lolginer/Albedo/files/1148921/user.zip)

**Comment by farazs** [comment]
It's definitely something in the config. Deleting it lets the app start again.

I just edited out the garbled stuff at the bottom and made it valid xml, and it worked! Thanks.

Not sure why the windows update messed it up though or if @ksbansal is encountering the same issue.

**Comment by farazs** [comment]
Though, there should probably be an error message if the config is corrupt, and/or a fresh new config should be made.

**Comment by ksbansal** [comment]
can you explain how you got it working. I don't understand what you did.

**Comment by farazs** [comment]
You will have to find the user.config file lolginer mentioned, then open it in an editor that can read that format, and edit it so that it is syntactically correct xml.

If that is difficult you can just delete the file and set up Albedo again, it should work after that.

**Comment by Lolginer** [comment]
Most of the settings file has been replaced with null characters. It's strange, but my guess is that Windows Update killed the program while it was in the middle of saving.

It's something I can add a check for, but the immediate fix is to do what farazs said.

**Comment by ksbansal** [comment]
I did a clean install making sure I delete all files. I even tried just deleting the config file. Still doesn't work ;(

**Comment by ksbansal** [comment]
Its working now thanks!
